### ISSUE TITLE
'notification_tag' is not a registered tag library

### ISSUE THREAD

**Issue by khansrk** [andybak/django-admin-notifications#3]
I am getting an error 
TemplateSyntaxError at /admin/

'notification_tag' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
i18n
l10n
log
static
staticfiles
tz

I don't know why it is happening can anyone help me

**Comment by andybak** [comment]
Hi. This was an internal project we open-sourced and you're the first person that has made us aware that anyone else is using it! So - apologies if there a are some rough edges. The documentation is probably lacking.

We're not actually using it in production any more. Can you check you have added 'admin_notifications' to INSTALLED_APPS?

**Comment by khansrk** [comment]
Yes I have added 'admin_notifications' to installed apps but still it is not working

**Comment by andybak** [comment]
I'm afraid I don't know then. As you can see the amount of code in this project is tiny so it should be fairly easy to debug at your end. Check the docs on custom template tags to see if that gives any clues: https://docs.djangoproject.com/en/1.10/howto/custom-template-tags/

We haven't used this in a while so it's possible it's related to changes in Django itself.

**Comment by khansrk** [comment]
Thanks @andybak for your help i will read the docs on custom template tags and get back to you shortly meanwhile if you get any solution so let me know

**Comment by khansrk** [comment]
Finally I got it.I was installing your app using pip and I found that only __init__.py file was installed in the site packages and there was a package on PyPI of your app but nothing was installed except __init__.py so I cloned the repository and it is working fine

**Comment by raratiru** [comment]
Count me in! 

`pip install -e git+https://github.com/andybak/django-admin-notifications@master#egg=django-admin-notifications`

It dId the trick in a wonderful manner!

Thank you @khansrk

**Comment by ghost** [comment]
![Screenshot from 2021-07-25 17-58-49](https://user-images.githubusercontent.com/82955418/126898957-909f430e-70b3-4ef9-a4cd-eb11a347f30e.png)

**Comment by andybak** [comment]
@hariomkuamwat - you've posted a screenshot without any accompanying message. I'm not sure what you're asking. This ticket has been closed for 4 years so it's probably not the right place to ask in any case.

I suggest opening a new ticket and write *at least* a few paragraphs explaining yourself.

**Comment by yashv25032** [comment]
TemplateSyntaxError at /users/my-account
'notification_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
convert_str_date
i18n
l10n
log
static
tz
